spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${AIVEN_REDIS_HOST}
      port: ${AIVEN_REDIS_PORT}
      username: ${AIVEN_REDIS_USERNAME}
      password: ${AIVEN_REDIS_PASSWORD}
      ssl:
        enabled: true
      timeout: 2s