spring:
  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${AIVEN_REDIS_HOST}
      port: ${AIVEN_REDIS_PORT}
      username: ${AIVEN_REDIS_USERNAME}
      password: ${AIVEN_REDIS_PASSWORD}
      ssl:
        enabled: true
      timeout: 2s