server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: studio-reservation-java

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_schema: studio
        format_sql: true

app:
  jwt:
    issuer: studio-reservation-back
    secret: ${JWT_SECRET}
    access-token-expiration: 30m
    refresh-token-expiration: 14d

  auth:
    refresh-cookie:
      secure: true
      same-site: None
      path: ${server.servlet.context-path:}/auth

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

logging:
  level:
    root: info